version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/MEAN-App
hooks:
  BeforeInstall:
    - location: foreverStop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: foreverStart.sh
      timeout: 300
      runas: ubuntu